USE travelmanager;

-- Xem CHECK constraint của bảng tours
SELECT CONSTRAINT_NAME, CHECK_CLAUSE
FROM INFORMATION_SCHEMA.CHECK_CONSTRAINTS
WHERE CONSTRAINT_SCHEMA = 'travelmanager'
AND CONSTRAINT_NAME LIKE 'tours%';
